// Bundles the ES modules under js/ into one classic script, js/tiles.bundle.js,
// so index.html also works when opened straight from disk (file://), where
// browsers refuse to load module scripts. Zero dependencies: the source only
// uses single-line `import { a, b } from './x.js'`, `import x from './x.js'`,
// `export function|const` and `export default`.
//
//   node build.js          write the bundle
//   node build.js --check  exit 1 if the committed bundle is out of date

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const entry = join(root, 'js/app.js');
const out = join(root, 'js/tiles.bundle.js');

const IMPORT = /^import\s+(?:\{([^}]*)\}|(\w+))\s+from\s+'([^']+)';\s*$/gm;

export function bundle() {
  const order = [];
  const seen = new Set();
  const visit = (file) => {
    if (seen.has(file)) return;
    seen.add(file);
    const src = readFileSync(file, 'utf8');
    for (const m of src.matchAll(IMPORT)) visit(resolve(dirname(file), m[3]));
    order.push(file);
  };
  visit(entry);

  const id = (file) => relative(root, file).replace(/\\/g, '/');
  const modules = order.map((file) => {
    let src = readFileSync(file, 'utf8');
    const exported = [];
    src = src.replace(IMPORT, (_, named, def, spec) => {
      const dep = JSON.stringify(id(resolve(dirname(file), spec)));
      if (def) return `const ${def} = __mods[${dep}].default;`;
      const parts = named
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .map((s) => s.replace(/^(\w+)\s+as\s+(\w+)$/, '$1: $2'));
      return `const { ${parts.join(', ')} } = __mods[${dep}];`;
    });
    src = src.replace(/^export\s+(async\s+function|function|const|let)\s+([\w$]+)/gm, (_, kind, name) => {
      exported.push(name);
      return `${kind} ${name}`;
    });
    src = src.replace(/^export\s+default\s+/m, () => {
      exported.push('default: __default');
      return 'const __default = ';
    });
    if (/^\s*(import|export)\s/m.test(src)) throw new Error(`Unsupported import/export form in ${id(file)}`);
    return `// ---- ${id(file)}\n__mods[${JSON.stringify(id(file))}] = (() => {\n${src.trimEnd()}\nreturn { ${exported.join(', ')} };\n})();`;
  });

  return `// Generated by build.js from js/**/*.js. Do not edit; run \`npm run build\`.\n(() => {\n'use strict';\nconst __mods = {};\n${modules.join('\n\n')}\n})();\n`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const code = bundle();
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(out, 'utf8');
    } catch {
      /* missing */
    }
    if (current !== code) {
      console.error('js/tiles.bundle.js is out of date. Run: npm run build');
      process.exit(1);
    }
    console.log('Bundle is up to date.');
  } else {
    writeFileSync(out, code);
    console.log(`Wrote ${relative(root, out)} (${(code.length / 1024).toFixed(1)} KB)`);
  }
}
