import { defineConfig } from 'vite';

// Builds the app into one classic (non-module) script, js/tiles.bundle.js.
// index.html loads it with a plain <script>, so the app also works when the
// file is opened straight from disk (file://), where browsers block module
// scripts.
export default defineConfig({
  build: {
    outDir: process.env.TILES_OUT_DIR ?? 'js',
    emptyOutDir: false,
    minify: false,
    sourcemap: false,
    target: 'es2022',
    lib: {
      entry: 'js/app.ts',
      formats: ['iife'],
      name: 'Tiles',
      fileName: () => 'tiles.bundle.js',
    },
    rollupOptions: { output: { banner: '// Generated by Vite from js/**/*. Do not edit; run `npm run build`.' } },
  },
  test: {
    include: ['test/**/*.test.{js,ts}'],
  },
});
