{{- if .Values.ingress.enabled }}
{{- $fullname := include "tiles.fullname" . }}
{{- $web := urlParse .Values.url }}
{{- $api := urlParse .Values.apiUrl }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "tiles.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tlsSecret }}
  tls:
    - hosts: [{{ (split ":" $web.host)._0 | quote }}, {{ (split ":" $api.host)._0 | quote }}]
      secretName: {{ . }}
  {{- end }}
  rules:
    - host: {{ (split ":" $web.host)._0 | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: {{ $fullname }}-web, port: { name: http } }
    - host: {{ (split ":" $api.host)._0 | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: {{ $fullname }}-api, port: { name: http } }
{{- end }}
