// Writes js/lib/icon-data.ts: the Lucide icons the app uses (the set shadcn/ui uses), copied from the
// lucide-static package at build time, so the browser app stays free of runtime dependencies.
// Add a name to NAMES and run `npm run icons`; test/icons.test.js fails when the file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

export const NAMES = [
  // Pages
  'house',
  'sparkles',
  'hard-hat',
  'factory',
  'network',
  'git-pull-request',
  'triangle-alert',
  'target',
  'gauge',
  'atom',
  'drafting-compass',
  'activity',
  'chart-line',
  'chart-scatter',
  'lightbulb',
  'layout-grid',
  'file-text',
  'upload',
  'rocket',
  'settings',
  // Controls and states
  'menu',
  'x',
  'sun',
  'moon',
  'search',
  'chevron-right',
  'chevron-down',
  'check',
  'plus',
  'trash-2',
  'pencil',
  'external-link',
  'info',
  'circle-alert',
  'circle-check',
  'circle-x',
  'circle-help',
  'loader-circle',
  'log-out',
  'copy',
  'download',
  'filter',
  'arrow-right',
  'bell',
  'command',
  'keyboard',
  'refresh-cw',
  'inbox',
  'git-commit-horizontal',
  'history',
  'zoom-in',
  'zoom-out',
  'maximize',
  'sliders-horizontal',
  'play',
  'square',
  'ellipsis',
  'send',
  'thumbs-up',
  'thumbs-down',
  'user',
  'users',
  'key-round',
  'shield',
  'plug',
  'cpu',
  'database',
  'book-open',
  'message-square',
  'undo-2',
  'redo-2',
  'save',
];

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);

export function generate() {
  const pkg = dirname(require.resolve('lucide-static/package.json'));
  const version = JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8')).version;
  const entries = NAMES.map((name) => {
    const svg = readFileSync(join(pkg, 'icons', `${name}.svg`), 'utf8');
    const body = svg
      .slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'))
      .replace(/\s*\n\s*/g, '')
      .trim();
    return `  '${name}': '${body.replace(/'/g, "\\'")}',`;
  });
  return `// Generated by scripts/icons.js from lucide-static ${version}: don't edit, run \`npm run icons\`.
// Lucide icons, https://lucide.dev. ISC License. Copyright (c) for portions of Lucide are held by
// Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for Lucide are held by
// Lucide Contributors 2022. Permission to use, copy, modify, and/or distribute this software for
// any purpose with or without fee is hereby granted, provided that the above copyright notice and
// this permission notice appear in all copies. THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
// DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE.

export const ICONS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICONS;
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(ROOT, 'js/lib/icon-data.ts'), generate());
  console.log(`js/lib/icon-data.ts: ${NAMES.length} icons`);
}
