// Icons (U1.05): Lucide's line icons (js/lib/icon-data.ts, generated by scripts/icons.js), drawn
// in the current text colour. Decorative by default: the text beside an icon names it; an icon
// that stands alone (an icon button) gets a `label`.
import { ICONS, type IconName } from './icon-data.ts';
import { esc } from './dom.ts';

export type { IconName };

export interface IconOptions {
  size?: number; // px; 16 by default, as shadcn/ui's
  label?: string; // the accessible name, when nothing else names it
  className?: string;
  strokeWidth?: number;
}

export function icon(name: IconName, opts: IconOptions = {}): string {
  const size = opts.size ?? 16;
  const a11y = opts.label ? `role="img" aria-label="${esc(opts.label)}"` : 'aria-hidden="true"';
  const cls = `icon icon-${name}${opts.className ? ` ${esc(opts.className)}` : ''}`;
  return `<svg class="${cls}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="${opts.strokeWidth ?? 2}" stroke-linecap="round" stroke-linejoin="round" focusable="false" ${a11y}>${ICONS[name]}</svg>`;
}

export const isIconName = (name: string): name is IconName => Object.hasOwn(ICONS, name);
